######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 29 21:08:50 2014
######################################################################

CONFIG += debug \
          qtestlib \
          testcase \
          create_prl \
          link_prl

QT += testlib gui widgets
TEMPLATE = app
TARGET = testsuite
DEPENDPATH += -L/usr/lib/x86_64-linux-gnu  \
              ../   \
              ./
INCLUDEPATH += ../  \
              ./

POST_TARGETDEPS += 

QMAKE_CLEAN += $(TARGET)

LIBS += ../debug/mapfileparser.o            \
        ../debug/outputformat.o             \
        ../debug/changemapnamecommand.o     \
        ../debug/layer.o                    \
        -L/usr/lib/x86_64-linux-gnu/ -lmapserver -lgdal -lgcov



# Input
HEADERS += testmapfileparser.h      \
           testlayer.h              \
           testoutputformat.h       \
           testcommands.h           \
           autotest.h

SOURCES += testmapfileparser.cpp    \
           testlayer.cpp            \
           testoutputformat.cpp     \
           testcommands.cpp         \
           main.cpp

