######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 29 21:08:50 2014
######################################################################

CONFIG += debug \
          qtestlib \
          testcase \
          create_prl \
          link_prl

QT += testlib gui
TEMPLATE = app
TARGET = test
DEPENDPATH += -L/usr/lib/x86_64-linux-gnu  \
              ../   \
              ./
INCLUDEPATH += ../  \
              ./

POST_TARGETDEPS += 

QMAKE_CLEAN += $(TARGET)

LIBS += ../debug/mapfileparser.o \
        ../debug/outputformat.o  \
        -L/usr/lib/x86_64-linux-gnu/ -lmapserver -lgdal -lgcov



# Input
HEADERS += testmapfileparser.h      \
           testoutputformat.h       \
           autotest.h

SOURCES += testmapfileparser.cpp    \
           testoutputformat.cpp     \
           main.cpp

